#!/bin/bash
git add . #komanda "uzmanaamo" mapju pievienosanai
git config --global user.name Robcons123
git config --global user.email Roberts.Cipruss@edu.rtu.lv
git commit -m "Class_06a"
git push origin main
